language: objective-c
notifications:
  email: false
  hipchat:
    rooms:
      secure: Yq2+XdiFlZ0vDrgw+EJ32pOplTZfN93bUXtFy/EgNoFNaRKXBOEpbKWmbwWaQzVUDDxO3mK2S3q1r+ifN2thEitLKqUuQQZV6g4cMaFZZKWSr+PCTMoGuo7IGkVDk3tEalCVy22mLtQ+S2Ol2GLAU6Ch2DHaEeN+EQqyTaMHlvdSFF+HvDXxgppeW938VQZJBpdxioEOF4e3t25eu9cjmR6jo/IdiNGXpWp3RboVe+tkWr+wjQx6QuUPdoKVxj7zW7zX8ZWBkh7ul3DDEykrM2pTTe+NsfkBEfap3K+hsX8PUNl+o3OhFZMpF3XgIc8+4D4AA1pxG0WzWItEwdcBecwCyrCIirxf2cqM0UzOAK7N5Wd8KUkDdS3m+8Go/+KmZhTtEJgQxcLa1odw6XXQ92kRWBSMfTXUcGYoyOJmwpYy+rYvijPoX9ukIy29e0TvBrLdZNJxlSplNkCmMJ9JQX2sxQ4A3c6I5AS+h3wCe6mF9rGhAEFqr1wp/qdb4iP2b/bXVC5onGP7y+9iwJzfQE0UomxGQM/dYUL7wC2X/qUj/h7oGfCLlkTsY88N7BV/NK0qwuXdS6tKljBr6QFRnG6qb8+9EJkc6A6kJBP9v0sGzPXCgdr85+n7FRLDzVNoYlmscZ4+fVdVQUILsqVmxwKx47HcALMAi47k1lroyJ4=

xcode_workspace: Avalon.xcworkspace
xcode_scheme: Avalon
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

