language: objective-c
notifications:
  email: false
  hipchat:
    rooms:
      secure: hmHocT9IsMIsFSSHuQpUc3DjejDODnU17OEyCiNi/x/4S1Phq3WONnCAnRlnm195FMr8thi+TPshKKfupkUk9XTDeZTdRAHuuNtpOqK5jQS/JUJju1DKCqGQ2zL4l05M0AMdn224pJ6oQoWz6pfNKQByTrmYvAvYd4WUulRxwxw/eoG+9IbhstiXKxW0qFFPUfjhQx5tXNTEMgVt91/beHTlFHsh4zj0ZUNYT8rdFREGnt5Q61SvJVwFboXM31a3w4KKMj40796Xb0ckYwCRFD4vy9sSINmiVkCVzikeuPztcY7ISdibAKnqnjXFPDzbz/cLMMPkeK0bdiQ7e+oeZ94hqmJd3d3b8H4FG1Y0Q3cU6dn7SOC2kDqsAzYKSEXt/DdFw0fayC6MsIMf27xrKHHXdthPzqKyCXsbyBLxOtBtKsCGz5tqBg+x8eGHR9wu5em4PPZ7StOMCkOXO83FBV52kDlYnPWj9whEsdoR8cCGGIExu3cgD8afCyhWrWV0Vh55awNbbXGV7YPtqIcsOxlJwJ7bN175NBp8Ta57KbCgYUhHKSKq8dH8GhNBYpys4JyqcLTEmcLK0ZvGZyuBjOjEdFxg6KwqhchG8uziY05D+FurBsMFAjjEOlC5xGag3GC4nTEJ8fH+FZ/DdaAkmv07qUIWLSdgGuXsSxRKlLY=

xcode_workspace: Dilemma.xcworkspace
xcode_scheme: Dilemma
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
