//
//  AvalonStyleKit.swift
//  Avalon
//
//  Created by Kyle Bashour on 1/27/16.
//  Copyright (c) 2016 Avalon Studios. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class AvalonStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfMutineersIcon: UIImage?
        static var mutineersIconTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawMutineersIcon() {
        //// Color Declarations
        let strokeColor = UIColor(red: 0.829, green: 0.000, blue: 0.034, alpha: 1.000)

        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(30, 16))
        bezier3Path.addCurveToPoint(CGPointMake(16, 30), controlPoint1: CGPointMake(30, 23.73), controlPoint2: CGPointMake(23.73, 30))
        bezier3Path.addCurveToPoint(CGPointMake(2, 16), controlPoint1: CGPointMake(8.27, 30), controlPoint2: CGPointMake(2, 23.73))
        bezier3Path.addCurveToPoint(CGPointMake(16, 2), controlPoint1: CGPointMake(2, 8.27), controlPoint2: CGPointMake(8.27, 2))
        bezier3Path.addCurveToPoint(CGPointMake(30, 16), controlPoint1: CGPointMake(23.73, 2), controlPoint2: CGPointMake(30, 8.27))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(2.87, 20.48))
        bezier3Path.addCurveToPoint(CGPointMake(9.95, 3.97), controlPoint1: CGPointMake(2.87, 20.48), controlPoint2: CGPointMake(11.77, 11.47))
        bezier3Path.addCurveToPoint(CGPointMake(15.94, 29.37), controlPoint1: CGPointMake(10.13, 2.43), controlPoint2: CGPointMake(15.94, 24.12))
        bezier3Path.moveToPoint(CGPointMake(29, 20.45))
        bezier3Path.addCurveToPoint(CGPointMake(21.92, 3.95), controlPoint1: CGPointMake(29, 20.45), controlPoint2: CGPointMake(20.1, 11.44))
        bezier3Path.addCurveToPoint(CGPointMake(15.94, 29.34), controlPoint1: CGPointMake(21.75, 2.4), controlPoint2: CGPointMake(15.94, 24.09))
        strokeColor.setStroke()
        bezier3Path.lineWidth = 3
        bezier3Path.stroke()
    }

    //// Generated Images

    public class var imageOfMutineersIcon: UIImage {
        if Cache.imageOfMutineersIcon != nil {
            return Cache.imageOfMutineersIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(32, 32), false, 0)
            AvalonStyleKit.drawMutineersIcon()

        Cache.imageOfMutineersIcon = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfMutineersIcon!
    }

    //// Customization Infrastructure

    @IBOutlet var mutineersIconTargets: [AnyObject]! {
        get { return Cache.mutineersIconTargets }
        set {
            Cache.mutineersIconTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: AvalonStyleKit.imageOfMutineersIcon)
            }
        }
    }

}
