//
//  Style.swift
//  Ascendant
//
//  Created by Kyle Bashour on 2/22/16.
//  Copyright (c) 2016 Kyle Bashour. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Style : NSObject {

    //// Cache

    private struct Cache {
        static let baseGrey: UIColor = UIColor(red: 0.222, green: 0.246, blue: 0.367, alpha: 1.000)
        static let darkBaseGrey: UIColor = UIColor(red: 0.155, green: 0.176, blue: 0.277, alpha: 1.000)
        static let red: UIColor = UIColor(red: 0.742, green: 0.230, blue: 0.230, alpha: 1.000)
        static let green: UIColor = UIColor(red: 0.250, green: 0.757, blue: 0.380, alpha: 1.000)
        static let blue: UIColor = UIColor(red: 0.247, green: 0.437, blue: 0.860, alpha: 1.000)
        static let transparentWhite: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.800)
    }

    //// Colors

    public class var baseGrey: UIColor { return Cache.baseGrey }
    public class var darkBaseGrey: UIColor { return Cache.darkBaseGrey }
    public class var red: UIColor { return Cache.red }
    public class var green: UIColor { return Cache.green }
    public class var blue: UIColor { return Cache.blue }
    public class var transparentWhite: UIColor { return Cache.transparentWhite }

}
